# OrangeFox Project Configs
OFOX_AB_DEVICE := true
OFOX_VIRTUAL_AB_DEVICE := true
FOX_VIRTUAL_AB_OTA := true
FOX_ENABLE_APP_MANAGER := true
FOX_USE_BASH_SHELL := true
FOX_ASH_IS_BASH := true
FOX_USE_NANO_EDITOR := true
FOX_USE_TAR_BINARY := true
FOX_USE_SED_BINARY := true
FOX_USE_XZ_UTILS := true
OFOX_KEEP_FORCED_ENCRYPTION := true
OFOX_NO_TREBLE_COMPATIBILITY_CHECK := true
OFOX_ALLOW_FRONT_CAMERA_FLASH := true
FOX_RECOVERY_INSTALL_PARTITION := "/vendor_boot"
FOX_RECOVERY_VENDOR_PARTITION := "/vendor"
FOX_RECOVERY_SYSTEM_PARTITION := "/system"
